"""Cover image generator using Gemini."""
from __future__ import annotations

import io
import os
from pathlib import Path
from typing import Final

from google import genai
from google.genai import types
from PIL import Image


class CoverGenerator:
    """Generates cover images in Hokusai ukiyo-e style."""

    _QUALITY: Final[int] = 85

    def __init__(self) -> None:
        """Initialize with Gemini client and load prompt spec."""
        self._client: Final[genai.Client] = genai.Client(
            api_key=os.environ["GEMINI_API_KEY"]
        )
        self._spec: Final[str] = self._load()

    def generate(self, topic: str, target: Path) -> Path:
        """Generate cover image for research topic at target path."""
        target.parent.mkdir(parents=True, exist_ok=True)
        response = self._client.models.generate_content(
            model="gemini-3-pro-image-preview",
            contents=self._prompt(topic),
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(
                    aspect_ratio="16:9",
                    image_size="1K",
                ),
            ),
        )
        for part in response.parts:
            raw = part.as_image()
            if raw:
                self._compress(raw, target)
                return target
        raise RuntimeError("No image generated by model")

    def _compress(self, source: types.Image, target: Path) -> None:
        """Compress image to JPEG with target quality."""
        buffer = io.BytesIO(source.image_bytes)
        image = Image.open(buffer)
        image.save(str(target), "JPEG", quality=self._QUALITY)

    def _load(self) -> str:
        """Load structured prompt template from JSON file."""
        path = Path(__file__).parent / "prompts" / "cover.json"
        return path.read_text(encoding="utf-8")

    def _prompt(self, topic: str) -> str:
        """Build prompt by substituting topic into template."""
        return self._spec % topic
