"""Cover image generator using Gemini."""
from __future__ import annotations

import io
import os
from pathlib import Path
from typing import Final

from google import genai
from google.genai import types
from PIL import Image


class CoverGenerator:
    """Generates cover images in Hokusai ukiyo-e style."""

    _QUALITY: Final[int] = 85

    def __init__(self, output: Path) -> None:
        """Initialize with output directory for covers."""
        self._output: Final[Path] = output
        self._client: Final[genai.Client] = genai.Client(
            api_key=os.environ["GEMINI_API_KEY"]
        )

    def generate(self, topic: str, identifier: str) -> Path:
        """Generate cover image for research topic."""
        self._output.mkdir(parents=True, exist_ok=True)
        response = self._client.models.generate_content(
            model="gemini-3-pro-image-preview",
            contents=self._prompt(topic),
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(
                    aspect_ratio="16:9",
                    image_size="1K",
                ),
            ),
        )
        path = self._output / f"{identifier}.jpg"
        for part in response.parts:
            raw = part.as_image()
            if raw:
                self._compress(raw, path)
                return path
        raise RuntimeError("No image generated by model")

    def _compress(self, source: types.Image, target: Path) -> None:
        """Compress image to JPEG with target quality."""
        buffer = io.BytesIO(source.image_bytes)
        image = Image.open(buffer)
        image.save(str(target), "JPEG", quality=self._QUALITY)

    def _prompt(self, topic: str) -> str:
        """Build prompt for Hokusai-style image."""
        return (
            "Edge-to-edge Japanese ukiyo-e woodblock print, 16:9 landscape cover illustration "
            f'of the concept: "{topic}", in the style of Katsushika Hokusai. '
            "This is the artwork itself, not a photo or mockup: no frame, no borders, no white "
            "margins, no wall, no room interior, no table, no hands, no poster or print mockup. "
            "Traditional Edo-period scene only. Modern topics are shown metaphorically through "
            "nature or spirits (mountains, waves, storms, clouds, scrolls, roots, spiderweb-like "
            "networks, lightning, mechanical clockwork), never as literal modern objects such as "
            "computers, phones, cars, trains, planes, skyscrapers, or contemporary clothing. "
            'Do not imitate "The Great Wave off Kanagawa": no huge curling foreground wave with '
            "boats; water, if present, is calm or secondary. "
            "Flat colors, bold expressive outlines, limited palette (deep Prussian blue, aged "
            "washi paper cream, faded vermilion, moss green), visible woodblock texture with "
            "subtle woodgrain, rough paper fibers and small organic imperfections; not vector, "
            "not glossy, not 3D, not digital UI. "
            "No text or letters in any language, no calligraphy, no captions, no logos, no "
            "watermarks, no signatures. Serene, minimal, timeless mood with generous negative space."
        )
