FROM clojure:temurin-21-lein

WORKDIR /app

COPY project.clj ./project.clj
COPY tests.edn ./tests.edn
RUN lein with-profile +test deps

COPY resources ./resources
COPY src ./src
COPY test ./test
COPY Dockerfile ./Dockerfile

ENTRYPOINT ["lein", "test"]
